apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      name: jaeger
      labels:
        app: jaeger
      annotations:
        date: "{{ .Release.Time.Seconds}}"
    spec:
      hostname: jaeger
      restartPolicy: Always
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.16
        env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
        - containerPort: 16686
        - containerPort: 16687
        - containerPort: 14268
        - containerPort: 9411
          
      