apiVersion: v1
kind: Service
metadata:
  name: sender
  labels:
    app: sender
spec:
  type: NodePort
  ports:
  - name: "input-trigger"
    port: 5000
    nodePort: 30001
  selector:
    app: sender